name: 'Auto Generate Release Changelog by Tag'
description: 'Auto Generate Release Changelog by Tag'
author: wxul
inputs:
  source_tag:
    description: Source Tag
    default: English
    required: true

  escape_break:
    description: Escape break
    required: false

  prefix:
    description: Tag prefix, for searching previous tag
    required: false

outputs:
  release_note:
    description: Release note markdown

runs:
  using: 'node20'
  main: 'lib/index.js'
